new-block-message: "#34eb77Congratulations ! #9eb3b5You have collected a new block #34ebdb%block%#9eb3b5."
all-block-message: "#34eb77Amazing ! #9eb3b5You have collected all the recoverable blocks in survival!"